<?php
/** @package DbHotel::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("CidadeMap.php");

/**
 * CidadeDAO provides object-oriented access to the tb_cidade table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DbHotel::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class CidadeDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;

	/** @var int */
	public $Estado;


	/**
	 * Returns a dataset of TbHospedagem objects with matching UltimaProcedenciaCidade
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetUltimaProcedenciaCidadeTbHospedagems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_hospedagem_tb_cidade1", $criteria);
	}

	/**
	 * Returns a dataset of TbHospedagem objects with matching ProxDestinoCidade
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetProxDestinoCidadeTbHospedagems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_hospedagem_tb_cidade2", $criteria);
	}

	/**
	 * Returns a dataset of TbHospede objects with matching Cidade
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCidadeTbHospedes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_hospede_tb_cidade", $criteria);
	}


}
?>