<?php
/** @package DbHotel::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("EstadoMap.php");

/**
 * EstadoDAO provides object-oriented access to the tb_estado table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DbHotel::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class EstadoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;

	/** @var string */
	public $Uf;

	/** @var int */
	public $Pais;


	/**
	 * Returns a dataset of TbHospedagem objects with matching UltimaProcedenciaEstado
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetUltimaProcedenciaEstadoTbHospedagems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_hospedagem_tb_estado1", $criteria);
	}

	/**
	 * Returns a dataset of TbHospedagem objects with matching ProxDestinoEstado
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetProxDestinoEstadoTbHospedagems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_hospedagem_tb_estado2", $criteria);
	}

	/**
	 * Returns a dataset of TbHospede objects with matching Estado
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetEstadoTbHospedes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_hospede_tb_estado1", $criteria);
	}


}
?>