<?php
/** @package DbHotel::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("HospedeMap.php");

/**
 * HospedeDAO provides object-oriented access to the tb_hospede table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DbHotel::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class HospedeDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Nome;

	/** @var date */
	public $DtNascimento;

	/** @var string */
	public $Telefone;

	/** @var string */
	public $Profissao;

	/** @var char */
	public $Sexo;

	/** @var int */
	public $Cidade;

	/** @var int */
	public $Estado;

	/** @var int */
	public $Pais;

	/** @var int */
	public $Cep;

	/** @var string */
	public $Endereco;

	/** @var int */
	public $TipoDocumento;

	/** @var string */
	public $NumDocumento;

	/** @var string */
	public $Email;


	/**
	 * Returns a dataset of TbHospedagem objects with matching Hospede
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetHospedeTbHospedagems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_hospedagem_tb_hospede1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Cidade
	 * @return TbCidade
	 */
	public function GetCidadeTbCidade()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospede_tb_cidade");
	}

	/**
	 * Returns the foreign object based on the value of Estado
	 * @return TbEstado
	 */
	public function GetEstadoTbEstado()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospede_tb_estado1");
	}

	/**
	 * Returns the foreign object based on the value of Pais
	 * @return TbPais
	 */
	public function GetPaisTbPais()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospede_tb_pais1");
	}

	/**
	 * Returns the foreign object based on the value of TipoDocumento
	 * @return TbTipoDocumento
	 */
	public function GetTipoDocumentoTbTipoDocumento()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospede_tb_tipo_documento1");
	}


}
?>