<?php
/** @package DbHotel::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("HospedagemMap.php");

/**
 * HospedagemDAO provides object-oriented access to the tb_hospedagem table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DbHotel::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class HospedagemDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $Hospede;

	/** @var char */
	public $TpHospede;

	/** @var int */
	public $Quarto;

	/** @var date */
	public $DtEntrada;

	/** @var date */
	public $DtSaida;

	/** @var int */
	public $MotivoViagem;

	/** @var int */
	public $MeioTransporte;

	/** @var int */
	public $UltimaProcedenciaPais;

	/** @var int */
	public $UltimaProcedenciaEstado;

	/** @var int */
	public $UltimaProcedenciaCidade;

	/** @var int */
	public $ProxDestinoPais;

	/** @var int */
	public $ProxDestinoEstado;

	/** @var int */
	public $ProxDestinoCidade;


	/**
	 * Returns the foreign object based on the value of UltimaProcedenciaCidade
	 * @return TbCidade
	 */
	public function GetUltimaProcedenciaCidadeTbCidade()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_cidade1");
	}

	/**
	 * Returns the foreign object based on the value of ProxDestinoCidade
	 * @return TbCidade
	 */
	public function GetProxDestinoCidadeTbCidade()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_cidade2");
	}

	/**
	 * Returns the foreign object based on the value of UltimaProcedenciaEstado
	 * @return TbEstado
	 */
	public function GetUltimaProcedenciaEstadoTbEstado()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_estado1");
	}

	/**
	 * Returns the foreign object based on the value of ProxDestinoEstado
	 * @return TbEstado
	 */
	public function GetProxDestinoEstadoTbEstado()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_estado2");
	}

	/**
	 * Returns the foreign object based on the value of Hospede
	 * @return TbHospede
	 */
	public function GetHospedeTbHospede()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_hospede1");
	}

	/**
	 * Returns the foreign object based on the value of MeioTransporte
	 * @return TbMeioTransporte
	 */
	public function GetMeioTransporteTbMeioTransporte()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_meio_transporte1");
	}

	/**
	 * Returns the foreign object based on the value of MotivoViagem
	 * @return TbMotivoViagem
	 */
	public function GetMotivoViagemTbMotivoViagem()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_motivo_viagem1");
	}

	/**
	 * Returns the foreign object based on the value of UltimaProcedenciaPais
	 * @return TbPais
	 */
	public function GetUltimaProcedenciaPaisTbPais()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_pais1");
	}

	/**
	 * Returns the foreign object based on the value of ProxDestinoPais
	 * @return TbPais
	 */
	public function GetProxDestinoPaisTbPais()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_pais2");
	}

	/**
	 * Returns the foreign object based on the value of Quarto
	 * @return TbQuarto
	 */
	public function GetQuartoTbQuarto()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_tb_hospedagem_tb_quarto1");
	}


}
?>