<?php
/** @package DbHotel::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("Tipo_de_DocumentoMap.php");

/**
 * Tipo_de_DocumentoDAO provides object-oriented access to the tb_tipo_documento table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package DbHotel::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class Tipo_de_DocumentoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Sigla;

	/** @var string */
	public $Nome;


	/**
	 * Returns a dataset of TbHospede objects with matching TipoDocumento
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetTipoDocumentoTbHospedes($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_tb_hospede_tb_tipo_documento1", $criteria);
	}


}
?>